name: validate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: hashicorp/setup-terraform@v2

    - run: terraform validate
    - run: terraform fmt -check
    - run: terraform init
